export const recipeList = [
    {
        id: '1',
        image: 'fried-chicken.jpg',
        title: 'Crispy Fried Chicken',
        totalTime: '30m',
        prep: '20m',
        chill: '00m',
        cook: '10m',
        recipeType: 'Non Vegetarian',
        ingredients: [
            {
                id: '1',
                name: 'Chicken',
                type: 'Tinned',
                quantity: '400g',
            },
            {
                id: '2',
                name: 'Garlic',
                type: 'Finely chopped',
                quantity: '50g',
            },
            {
                id: '3',
                name: 'Ginger',
                type: 'Finely chopped',
                quantity: '500g',
            },
        ],
        instructions: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil sapiente nulla veritatis atque quo adipisci eaque in tenetur voluptate, iste consequatur cum autem quod iusto ipsam eius corrupti nesciunt facere laborum odit saepe repellat nobis. Eius vel explicabo perspiciatis reiciendis velit fugiat, similique iusto delectus dicta rerum eaque alias inventore voluptatum unde praesentium doloremque est dignissimos, hic rem maxime voluptatibus quibusdam in ex? Cumque eum quo ratione cupiditate illum nostrum sit exercitationem fugiat! Quaerat suscipit harum nihil odio qui explicabo placeat aliquam tempora vitae iure. Eum optio, quibusdam ea beatae temporibus voluptate, repudiandae omnis quis ducimus ipsum minus recusandae perspiciatis.',
    },
    {
        id: '2',
        image: 'pasta.jpg',
        title: 'Tomato Pasta',
        totalTime: '30m',
        prep: '20m',
        chill: '00m',
        cook: '10m',
        recipeType: 'Vegetarian',
        ingredients: [
            {
                id: '1',
                name: 'Pasta',
                type: 'Boiled',
                quantity: '500g',
            },
            {
                id: '2',
                name: 'Tomatoes',
                type: 'Chopped',
                quantity: '100g',
            },
            {
                id: '3',
                name: 'Coriander',
                type: 'Chopped',
                quantity: '10g',
            },
        ],
        instructions: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil sapiente nulla veritatis atque quo adipisci eaque in tenetur voluptate, iste consequatur cum autem quod iusto ipsam eius corrupti nesciunt facere laborum odit saepe repellat nobis. Eius vel explicabo perspiciatis reiciendis velit fugiat, similique iusto delectus dicta rerum eaque alias inventore voluptatum unde praesentium doloremque est dignissimos, hic rem maxime voluptatibus quibusdam in ex? Cumque eum quo ratione cupiditate illum nostrum sit exercitationem fugiat! Quaerat suscipit harum nihil odio qui explicabo placeat aliquam tempora vitae iure. Eum optio, quibusdam ea beatae temporibus voluptate, repudiandae omnis quis ducimus ipsum minus recusandae perspiciatis.',
    },
    {
        id: '3',
        image: 'pizza1.jpg',
        title: 'Sausage Pizza',
        totalTime: '30m',
        prep: '20m',
        chill: '00m',
        cook: '10m',
        recipeType: 'Non Vegetarian',
        ingredients: [
            {
                id: '1',
                name: 'Flour',
                type: 'Knead',
                quantity: '500g',
            },
            {
                id: '2',
                name: 'Sausage',
                type: 'Sliced',
                quantity: '400g',
            },
            {
                id: '3',
                name: 'Olives',
                type: 'Chopped',
                quantity: '50g',
            },
            {
                id: '4',
                name: 'Cheese',
                type: 'Grated',
                quantity: '100g',
            },
        ],
        instructions: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil sapiente nulla veritatis atque quo adipisci eaque in tenetur voluptate, iste consequatur cum autem quod iusto ipsam eius corrupti nesciunt facere laborum odit saepe repellat nobis. Eius vel explicabo perspiciatis reiciendis velit fugiat, similique iusto delectus dicta rerum eaque alias inventore voluptatum unde praesentium doloremque est dignissimos, hic rem maxime voluptatibus quibusdam in ex? Cumque eum quo ratione cupiditate illum nostrum sit exercitationem fugiat! Quaerat suscipit harum nihil odio qui explicabo placeat aliquam tempora vitae iure. Eum optio, quibusdam ea beatae temporibus voluptate, repudiandae omnis quis ducimus ipsum minus recusandae perspiciatis.',
    },
    {
        id: '4',
        image: 'mexican-tacos.jpg',
        title: 'Mexican Tacos',
        totalTime: '20m',
        prep: '10m',
        chill: '00m',
        cook: '15m',
        recipeType: 'Vegetarian',
        ingredients: [
            {
                id: '1',
                name: 'Green vegetables',
                type: 'Chopped',
                quantity: '500g',
            },
            {
                id: '2',
                name: 'Chopped tomatoes',
                type: 'Tinned',
                quantity: '400g',
            },
            {
                id: '3',
                name: 'Coriander',
                type: 'Chopped',
                quantity: '50g',
            },
            {
                id: '4',
                name: 'Onions',
                type: 'Sliced',
                quantity: '100g',
            },
        ],
        instructions: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nihil sapiente nulla veritatis atque quo adipisci eaque in tenetur voluptate, iste consequatur cum autem quod iusto ipsam eius corrupti nesciunt facere laborum odit saepe repellat nobis. Eius vel explicabo perspiciatis reiciendis velit fugiat, similique iusto delectus dicta rerum eaque alias inventore voluptatum unde praesentium doloremque est dignissimos, hic rem maxime voluptatibus quibusdam in ex? Cumque eum quo ratione cupiditate illum nostrum sit exercitationem fugiat! Quaerat suscipit harum nihil odio qui explicabo placeat aliquam tempora vitae iure. Eum optio, quibusdam ea beatae temporibus voluptate, repudiandae omnis quis ducimus ipsum minus recusandae perspiciatis.',
    },
];